apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-externaluser-factory
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-externaluser-factory:latest
  imagePullPolicy: Always
  env:
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
